//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Castor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A (Alpha): ähnelt.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle geöffneten Dateien wurden abgespeichert. ähnelt.
        /// </summary>
        internal static string AlleDateienGespeichertNachricht {
            get {
                return ResourceManager.GetString("AlleDateienGespeichertNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles Schließen ähnelt.
        /// </summary>
        internal static string AlleSchließen {
            get {
                return ResourceManager.GetString("AlleSchließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles Speichern ähnelt.
        /// </summary>
        internal static string AlleSpeichern {
            get {
                return ResourceManager.GetString("AlleSpeichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        internal static string Ansicht {
            get {
                return ResourceManager.GetString("Ansicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erscheinung ähnelt.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwenden ähnelt.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B (Blau): ähnelt.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Baum ähnelt.
        /// </summary>
        internal static string BaumTemplate_Header {
            get {
                return ResourceManager.GetString("BaumTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Stufen: ähnelt.
        /// </summary>
        internal static string BaumTemplate_StufenText {
            get {
                return ResourceManager.GetString("BaumTemplate_StufenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Baum mit m Stufen und n Verzweigungen pro Stufe. ähnelt.
        /// </summary>
        internal static string BaumTemplate_Text {
            get {
                return ResourceManager.GetString("BaumTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Verzweigungen: ähnelt.
        /// </summary>
        internal static string BaumTemplate_VerzweigungenText {
            get {
                return ResourceManager.GetString("BaumTemplate_VerzweigungenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string Bearbeiten {
            get {
                return ResourceManager.GetString("Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        internal static string Bestätigen {
            get {
                return ResourceManager.GetString("Bestätigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollständiger bipartiter Graph ähnelt.
        /// </summary>
        internal static string BipartiterGraphTemplate_Header {
            get {
                return ResourceManager.GetString("BipartiterGraphTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten in erster Menge: ähnelt.
        /// </summary>
        internal static string BipartiterGraphTemplate_Knoten1Text {
            get {
                return ResourceManager.GetString("BipartiterGraphTemplate_Knoten1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten in zweiter Menge: ähnelt.
        /// </summary>
        internal static string BipartiterGraphTemplate_Knoten2Text {
            get {
                return ResourceManager.GetString("BipartiterGraphTemplate_Knoten2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein vollständiger bipartiter m-n-Graph. ähnelt.
        /// </summary>
        internal static string BipartiterGraphTemplate_Text {
            get {
                return ResourceManager.GetString("BipartiterGraphTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreis ähnelt.
        /// </summary>
        internal static string CircleTemplate_Header {
            get {
                return ResourceManager.GetString("CircleTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten: ähnelt.
        /// </summary>
        internal static string CircleTemplate_KnotenText {
            get {
                return ResourceManager.GetString("CircleTemplate_KnotenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Kreis mit n-Knoten. ähnelt.
        /// </summary>
        internal static string CircleTemplate_Text {
            get {
                return ResourceManager.GetString("CircleTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konsole ähnelt.
        /// </summary>
        internal static string ConsoleHeaderText {
            get {
                return ResourceManager.GetString("ConsoleHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string Datei {
            get {
                return ResourceManager.GetString("Datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei wurde geöffnet:  ähnelt.
        /// </summary>
        internal static string DateiGeöffnetNachricht {
            get {
                return ResourceManager.GetString("DateiGeöffnetNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei konnte nicht geöffnet werden:  ähnelt.
        /// </summary>
        internal static string DateiNichtGeöffnetNachricht {
            get {
                return ResourceManager.GetString("DateiNichtGeöffnetNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne eine Datei ähnelt.
        /// </summary>
        internal static string DateiÖffnen {
            get {
                return ResourceManager.GetString("DateiÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei wurde abgespeichert:  ähnelt.
        /// </summary>
        internal static string DateiSpeichernNachricht {
            get {
                return ResourceManager.GetString("DateiSpeichernNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design der Kanten ähnelt.
        /// </summary>
        internal static string Edge_Design_Text {
            get {
                return ResourceManager.GetString("Edge_Design_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe der Kanten: ähnelt.
        /// </summary>
        internal static string Edge_DesignBorder_Text {
            get {
                return ResourceManager.GetString("Edge_DesignBorder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanten: ähnelt.
        /// </summary>
        internal static string Edge_DesignSizes_Text {
            get {
                return ResourceManager.GetString("Edge_DesignSizes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaft ähnelt.
        /// </summary>
        internal static string Eigenschaft {
            get {
                return ResourceManager.GetString("Eigenschaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaft: ähnelt.
        /// </summary>
        internal static string EigenschaftDataGrid {
            get {
                return ResourceManager.GetString("EigenschaftDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften ähnelt.
        /// </summary>
        internal static string Eigenschaften {
            get {
                return ResourceManager.GetString("Eigenschaften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften-Fenster ähnelt.
        /// </summary>
        internal static string EigenschaftenFenster {
            get {
                return ResourceManager.GetString("EigenschaftenFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Eigenschaften-Fenster wurde geöffnet. ähnelt.
        /// </summary>
        internal static string EigenschaftenFensterÖffnenNachricht {
            get {
                return ResourceManager.GetString("EigenschaftenFensterÖffnenNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne ihre Eigenschaften ähnelt.
        /// </summary>
        internal static string EigenschaftenKante {
            get {
                return ResourceManager.GetString("EigenschaftenKante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne seine Eigenschaften ähnelt.
        /// </summary>
        internal static string EigenschaftenKnoten {
            get {
                return ResourceManager.GetString("EigenschaftenKnoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Eigenschaften des Graphen... ähnelt.
        /// </summary>
        internal static string EigenschaftenLaden {
            get {
                return ResourceManager.GetString("EigenschaftenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string Einstellungen {
            get {
                return ResourceManager.GetString("Einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string EinstellungenTitle {
            get {
                return ResourceManager.GetString("EinstellungenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string EinstellungsFenster {
            get {
                return ResourceManager.GetString("EinstellungsFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheinbar sind die Einstellungen nicht richtig! ähnelt.
        /// </summary>
        internal static string ErrorEinstellungen {
            get {
                return ResourceManager.GetString("ErrorEinstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellen ähnelt.
        /// </summary>
        internal static string Erstelle {
            get {
                return ResourceManager.GetString("Erstelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Datei erstellen: ähnelt.
        /// </summary>
        internal static string ErstelleNeueDatei {
            get {
                return ResourceManager.GetString("ErstelleNeueDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ist möglicherweise beschädigt oder unvollständig. Dadurch kann der Graph auch unvollständig sein. ähnelt.
        /// </summary>
        internal static string FehlermeldungBeschädigteDatei {
            get {
                return ResourceManager.GetString("FehlermeldungBeschädigteDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster ähnelt.
        /// </summary>
        internal static string Fenster {
            get {
                return ResourceManager.GetString("Fenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftart: ähnelt.
        /// </summary>
        internal static string FontFamilyPickerText {
            get {
                return ResourceManager.GetString("FontFamilyPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgröße: ähnelt.
        /// </summary>
        internal static string FontSizeBoxText {
            get {
                return ResourceManager.GetString("FontSizeBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G (Grün): ähnelt.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pollux - Neuen Graph hinzufügen ähnelt.
        /// </summary>
        internal static string GraphAuswahlHeader {
            get {
                return ResourceManager.GetString("GraphAuswahlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graph bearbeiten ähnelt.
        /// </summary>
        internal static string GraphBearbeiten {
            get {
                return ResourceManager.GetString("GraphBearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstelle einen neuen Graphen ähnelt.
        /// </summary>
        internal static string GraphErstellen {
            get {
                return ResourceManager.GetString("GraphErstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden des Fensters... ähnelt.
        /// </summary>
        internal static string GraphLaden {
            get {
                return ResourceManager.GetString("GraphLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne einen Graphen (.poll-Datei) ähnelt.
        /// </summary>
        internal static string GraphÖffnen {
            get {
                return ResourceManager.GetString("GraphÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graph ähnelt.
        /// </summary>
        internal static string GraphTab_Header {
            get {
                return ResourceManager.GetString("GraphTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Darstellung der Konsole ähnelt.
        /// </summary>
        internal static string HeaderConsoleText {
            get {
                return ResourceManager.GetString("HeaderConsoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string Hilfe {
            get {
                return ResourceManager.GetString("Hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bekomme Hilfe ähnelt.
        /// </summary>
        internal static string HilfeDateiÖffnen {
            get {
                return ResourceManager.GetString("HilfeDateiÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante hinzufügen ähnelt.
        /// </summary>
        internal static string KanteHinzufügen {
            get {
                return ResourceManager.GetString("KanteHinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante löschen ähnelt.
        /// </summary>
        internal static string KanteLöschenContent {
            get {
                return ResourceManager.GetString("KanteLöschenContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanten: ähnelt.
        /// </summary>
        internal static string Kanten {
            get {
                return ResourceManager.GetString("Kanten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design der Kante ähnelt.
        /// </summary>
        internal static string Kanten_Design_Text {
            get {
                return ResourceManager.GetString("Kanten_Design_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe der Kante ähnelt.
        /// </summary>
        internal static string Kanten_DesignBorder_Text {
            get {
                return ResourceManager.GetString("Kanten_DesignBorder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante: ähnelt.
        /// </summary>
        internal static string Kanten_DesignSizes_Text {
            get {
                return ResourceManager.GetString("Kanten_DesignSizes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau der Kanten: ähnelt.
        /// </summary>
        internal static string Kanten_Preview_Text {
            get {
                return ResourceManager.GetString("Kanten_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende: ähnelt.
        /// </summary>
        internal static string KantenEndeText {
            get {
                return ResourceManager.GetString("KantenEndeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Kanten des Graphen... ähnelt.
        /// </summary>
        internal static string KantenLaden {
            get {
                return ResourceManager.GetString("KantenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string KantenNameText {
            get {
                return ResourceManager.GetString("KantenNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eltern: ähnelt.
        /// </summary>
        internal static string KantenParentText {
            get {
                return ResourceManager.GetString("KantenParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl Kante: ähnelt.
        /// </summary>
        internal static string KantenPickerText {
            get {
                return ResourceManager.GetString("KantenPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau der Schlingen: ähnelt.
        /// </summary>
        internal static string KantenSchlinge_Preview_Text {
            get {
                return ResourceManager.GetString("KantenSchlinge_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        internal static string KantenStartText {
            get {
                return ResourceManager.GetString("KantenStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanten ähnelt.
        /// </summary>
        internal static string KantenTab_Header {
            get {
                return ResourceManager.GetString("KantenTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieht so aus als würde dieser Graph keine Kanten beinhalten! ähnelt.
        /// </summary>
        internal static string KeineKanten {
            get {
                return ResourceManager.GetString("KeineKanten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieht so aus als würde dieser Graph keine Knoten beinhalten! ähnelt.
        /// </summary>
        internal static string KeineKnoten {
            get {
                return ResourceManager.GetString("KeineKnoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten: ähnelt.
        /// </summary>
        internal static string Knoten {
            get {
                return ResourceManager.GetString("Knoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design des Knotens ähnelt.
        /// </summary>
        internal static string Knoten_Design_Text {
            get {
                return ResourceManager.GetString("Knoten_Design_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe des Randes des Knotens: ähnelt.
        /// </summary>
        internal static string Knoten_DesignBorder_Text {
            get {
                return ResourceManager.GetString("Knoten_DesignBorder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe der Füllung des Knotens: ähnelt.
        /// </summary>
        internal static string Knoten_DesignFilling_Text {
            get {
                return ResourceManager.GetString("Knoten_DesignFilling_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übergang ähnelt.
        /// </summary>
        internal static string Knoten_DesignFilling2_CheckBox {
            get {
                return ResourceManager.GetString("Knoten_DesignFilling2_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten: ähnelt.
        /// </summary>
        internal static string Knoten_DesignSizes_Text {
            get {
                return ResourceManager.GetString("Knoten_DesignSizes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau der Knoten: ähnelt.
        /// </summary>
        internal static string Knoten_Preview_Text {
            get {
                return ResourceManager.GetString("Knoten_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erster Knoten: ähnelt.
        /// </summary>
        internal static string Knoten1 {
            get {
                return ResourceManager.GetString("Knoten1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zweiter Knoten: ähnelt.
        /// </summary>
        internal static string Knoten2 {
            get {
                return ResourceManager.GetString("Knoten2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grad: ähnelt.
        /// </summary>
        internal static string KnotenGradText {
            get {
                return ResourceManager.GetString("KnotenGradText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten hinzufügen ähnelt.
        /// </summary>
        internal static string KnotenHinzufügen {
            get {
                return ResourceManager.GetString("KnotenHinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanten: ähnelt.
        /// </summary>
        internal static string KnotenKantenText {
            get {
                return ResourceManager.GetString("KnotenKantenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten löschen ähnelt.
        /// </summary>
        internal static string KnotenLöschenContent {
            get {
                return ResourceManager.GetString("KnotenLöschenContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string KnotenNameText {
            get {
                return ResourceManager.GetString("KnotenNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eltern: ähnelt.
        /// </summary>
        internal static string KnotenParentText {
            get {
                return ResourceManager.GetString("KnotenParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl Knoten: ähnelt.
        /// </summary>
        internal static string KnotenPickerText {
            get {
                return ResourceManager.GetString("KnotenPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten ähnelt.
        /// </summary>
        internal static string KnotenTab_Header {
            get {
                return ResourceManager.GetString("KnotenTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Knoten des Graphen... ähnelt.
        /// </summary>
        internal static string KontenLaden {
            get {
                return ResourceManager.GetString("KontenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt genutzte Dateien: ähnelt.
        /// </summary>
        internal static string LetzteDateien {
            get {
                return ResourceManager.GetString("LetzteDateien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante entfernen ähnelt.
        /// </summary>
        internal static string LöschenKante {
            get {
                return ResourceManager.GetString("LöschenKante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten entfernen ähnelt.
        /// </summary>
        internal static string LöschenKnoten {
            get {
                return ResourceManager.GetString("LöschenKnoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
        /// </summary>
        internal static string Neu {
            get {
                return ResourceManager.GetString("Neu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string NeueDateiName {
            get {
                return ResourceManager.GetString("NeueDateiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Tab ähnelt.
        /// </summary>
        internal static string NeuerTab {
            get {
                return ResourceManager.GetString("NeuerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Fenster ähnelt.
        /// </summary>
        internal static string NeuesFenster {
            get {
                return ResourceManager.GetString("NeuesFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design der Knoten ähnelt.
        /// </summary>
        internal static string Node_Design_Text {
            get {
                return ResourceManager.GetString("Node_Design_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe des Randes der Knoten: ähnelt.
        /// </summary>
        internal static string Node_DesignBorder_Text {
            get {
                return ResourceManager.GetString("Node_DesignBorder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe der Füllung der Knoten: ähnelt.
        /// </summary>
        internal static string Node_DesignFilling_Text {
            get {
                return ResourceManager.GetString("Node_DesignFilling_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übergang ähnelt.
        /// </summary>
        internal static string Node_DesignFilling2_CheckBox {
            get {
                return ResourceManager.GetString("Node_DesignFilling2_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten: ähnelt.
        /// </summary>
        internal static string Node_DesignSizes_Text {
            get {
                return ResourceManager.GetString("Node_DesignSizes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Vorlage ähnelt.
        /// </summary>
        internal static string NothingTemplate_Header {
            get {
                return ResourceManager.GetString("NothingTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein leerer Graph ohne eine Vorlage. ähnelt.
        /// </summary>
        internal static string NothingTemplate_Text {
            get {
                return ResourceManager.GetString("NothingTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        internal static string Öffnen {
            get {
                return ResourceManager.GetString("Öffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau: ähnelt.
        /// </summary>
        internal static string Preview_Text {
            get {
                return ResourceManager.GetString("Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau: ähnelt.
        /// </summary>
        internal static string PreviewConsoleText {
            get {
                return ResourceManager.GetString("PreviewConsoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die R (Rot): ähnelt.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als Bild speichern ähnelt.
        /// </summary>
        internal static string SaveAsSVG {
            get {
                return ResourceManager.GetString("SaveAsSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string Schließen {
            get {
                return ResourceManager.GetString("Schließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dicke: ähnelt.
        /// </summary>
        internal static string Slider_Edge_SizeStroke_Text {
            get {
                return ResourceManager.GetString("Slider_Edge_SizeStroke_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dicke: ähnelt.
        /// </summary>
        internal static string Slider_Kanten_SizeStroke_Text {
            get {
                return ResourceManager.GetString("Slider_Kanten_SizeStroke_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe: ähnelt.
        /// </summary>
        internal static string Slider_Knoten_Size_Text {
            get {
                return ResourceManager.GetString("Slider_Knoten_Size_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rand: ähnelt.
        /// </summary>
        internal static string Slider_Knoten_SizeStroke_Text {
            get {
                return ResourceManager.GetString("Slider_Knoten_SizeStroke_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe: ähnelt.
        /// </summary>
        internal static string Slider_Node_Size_Text {
            get {
                return ResourceManager.GetString("Slider_Node_Size_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rand: ähnelt.
        /// </summary>
        internal static string Slider_Node_SizeStroke_Text {
            get {
                return ResourceManager.GetString("Slider_Node_SizeStroke_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string Speichern {
            get {
                return ResourceManager.GetString("Speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort: ähnelt.
        /// </summary>
        internal static string Speicherort {
            get {
                return ResourceManager.GetString("Speicherort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Tabelle des Graphen... ähnelt.
        /// </summary>
        internal static string TabelleLaden {
            get {
                return ResourceManager.GetString("TabelleLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Tab wurde geschlossen. ähnelt.
        /// </summary>
        internal static string TabGeschlossenNachricht {
            get {
                return ResourceManager.GetString("TabGeschlossenNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließe Tab ähnelt.
        /// </summary>
        internal static string TabSchließen {
            get {
                return ResourceManager.GetString("TabSchließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagen: ähnelt.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pollux - neues Fenster ähnelt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um Änderungen anzuwenden muss die Anwendung neugestartet werden. ähnelt.
        /// </summary>
        internal static string ToolTipApply {
            get {
                return ResourceManager.GetString("ToolTipApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzen der Texte... ähnelt.
        /// </summary>
        internal static string Überstezen {
            get {
                return ResourceManager.GetString("Überstezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante umbennen ähnelt.
        /// </summary>
        internal static string UmbennenKanten {
            get {
                return ResourceManager.GetString("UmbennenKanten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten umbennen ähnelt.
        /// </summary>
        internal static string UmbennenKnoten {
            get {
                return ResourceManager.GetString("UmbennenKnoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vieleck ähnelt.
        /// </summary>
        internal static string VieleckTemplate_Header {
            get {
                return ResourceManager.GetString("VieleckTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten: ähnelt.
        /// </summary>
        internal static string VieleckTemplate_KnotenText {
            get {
                return ResourceManager.GetString("VieleckTemplate_KnotenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Vieleck mit n-Knoten. ähnelt.
        /// </summary>
        internal static string VieleckTemplate_Text {
            get {
                return ResourceManager.GetString("VieleckTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollständiges Vieleck ähnelt.
        /// </summary>
        internal static string VollständigesVieleckTemplate_Header {
            get {
                return ResourceManager.GetString("VollständigesVieleckTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten: ähnelt.
        /// </summary>
        internal static string VollständigesVieleckTemplate_KnotenText {
            get {
                return ResourceManager.GetString("VollständigesVieleckTemplate_KnotenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Vollständiges Vieleck mit n-Knoten. ähnelt.
        /// </summary>
        internal static string VollständigesVieleckTemplate_Text {
            get {
                return ResourceManager.GetString("VollständigesVieleckTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort ähnelt.
        /// </summary>
        internal static string Weg {
            get {
                return ResourceManager.GetString("Weg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert ähnelt.
        /// </summary>
        internal static string Wert {
            get {
                return ResourceManager.GetString("Wert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert: ähnelt.
        /// </summary>
        internal static string WertDataGrid {
            get {
                return ResourceManager.GetString("WertDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen! ähnelt.
        /// </summary>
        internal static string Willkommen {
            get {
                return ResourceManager.GetString("Willkommen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herzlich Willkommen bei Pollux! ähnelt.
        /// </summary>
        internal static string Willkommenstext {
            get {
                return ResourceManager.GetString("Willkommenstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasst uns loslegen, indem wir einen neuen Graphen erstellen. ähnelt.
        /// </summary>
        internal static string Willkommenstext2 {
            get {
                return ResourceManager.GetString("Willkommenstext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwischen Tabs springen ähnelt.
        /// </summary>
        internal static string ZwischenTabsSpringen {
            get {
                return ResourceManager.GetString("ZwischenTabsSpringen", resourceCulture);
            }
        }
    }
}
