//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollux.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pollux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles Schließen ähnelt.
        /// </summary>
        public static string AlleSchließen {
            get {
                return ResourceManager.GetString("AlleSchließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles Speichern ähnelt.
        /// </summary>
        public static string AlleSpeichern {
            get {
                return ResourceManager.GetString("AlleSpeichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        public static string Ansicht {
            get {
                return ResourceManager.GetString("Ansicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Bearbeiten {
            get {
                return ResourceManager.GetString("Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        public static string Bestätigen {
            get {
                return ResourceManager.GetString("Bestätigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreis ähnelt.
        /// </summary>
        public static string CircleTemplate_Header {
            get {
                return ResourceManager.GetString("CircleTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten: ähnelt.
        /// </summary>
        public static string CircleTemplate_KnotenText {
            get {
                return ResourceManager.GetString("CircleTemplate_KnotenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Kreis mit n-Knoten. ähnelt.
        /// </summary>
        public static string CircleTemplate_Text {
            get {
                return ResourceManager.GetString("CircleTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string Datei {
            get {
                return ResourceManager.GetString("Datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne eine Datei ähnelt.
        /// </summary>
        public static string DateiÖffnen {
            get {
                return ResourceManager.GetString("DateiÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaft ähnelt.
        /// </summary>
        public static string Eigenschaft {
            get {
                return ResourceManager.GetString("Eigenschaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften ähnelt.
        /// </summary>
        public static string Eigenschaften {
            get {
                return ResourceManager.GetString("Eigenschaften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften-Fenster ähnelt.
        /// </summary>
        public static string EigenschaftenFenster {
            get {
                return ResourceManager.GetString("EigenschaftenFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Eigenschaften des Graphen... ähnelt.
        /// </summary>
        public static string EigenschaftenLaden {
            get {
                return ResourceManager.GetString("EigenschaftenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Einstellungen {
            get {
                return ResourceManager.GetString("Einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string EinstellungsFenster {
            get {
                return ResourceManager.GetString("EinstellungsFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellen ähnelt.
        /// </summary>
        public static string Erstelle {
            get {
                return ResourceManager.GetString("Erstelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Datei erstellen: ähnelt.
        /// </summary>
        public static string ErstelleNeueDatei {
            get {
                return ResourceManager.GetString("ErstelleNeueDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ist möglicherweise beschädigt oder unvollständig. Dadurch kann der Graph auch unvollständig sein. ähnelt.
        /// </summary>
        public static string FehlermeldungBeschädigteDatei {
            get {
                return ResourceManager.GetString("FehlermeldungBeschädigteDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster ähnelt.
        /// </summary>
        public static string Fenster {
            get {
                return ResourceManager.GetString("Fenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pollux - Neuen Graph hinzufügen ähnelt.
        /// </summary>
        public static string GraphAuswahlHeader {
            get {
                return ResourceManager.GetString("GraphAuswahlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graph bearbeiten ähnelt.
        /// </summary>
        public static string GraphBearbeiten {
            get {
                return ResourceManager.GetString("GraphBearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstelle einen neuen Graphen ähnelt.
        /// </summary>
        public static string GraphErstellen {
            get {
                return ResourceManager.GetString("GraphErstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden des Fensters... ähnelt.
        /// </summary>
        public static string GraphLaden {
            get {
                return ResourceManager.GetString("GraphLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne einen Graphen (.poll-Datei) ähnelt.
        /// </summary>
        public static string GraphÖffnen {
            get {
                return ResourceManager.GetString("GraphÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string Hilfe {
            get {
                return ResourceManager.GetString("Hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bekomme Hilfe ähnelt.
        /// </summary>
        public static string HilfeDateiÖffnen {
            get {
                return ResourceManager.GetString("HilfeDateiÖffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kante hinzufügen ähnelt.
        /// </summary>
        public static string KanteHinzufügen {
            get {
                return ResourceManager.GetString("KanteHinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende: ähnelt.
        /// </summary>
        public static string KantenEndeText {
            get {
                return ResourceManager.GetString("KantenEndeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Kanten des Graphen... ähnelt.
        /// </summary>
        public static string KantenLaden {
            get {
                return ResourceManager.GetString("KantenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string KantenNameText {
            get {
                return ResourceManager.GetString("KantenNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eltern: ähnelt.
        /// </summary>
        public static string KantenParentText {
            get {
                return ResourceManager.GetString("KantenParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl Kante: ähnelt.
        /// </summary>
        public static string KantenPickerText {
            get {
                return ResourceManager.GetString("KantenPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        public static string KantenStartText {
            get {
                return ResourceManager.GetString("KantenStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieht so aus als würde dieser Graph keine Knoten beinhalten! ähnelt.
        /// </summary>
        public static string KeineKanten {
            get {
                return ResourceManager.GetString("KeineKanten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erster Knoten: ähnelt.
        /// </summary>
        public static string Knoten1 {
            get {
                return ResourceManager.GetString("Knoten1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zweiter Knoten: ähnelt.
        /// </summary>
        public static string Knoten2 {
            get {
                return ResourceManager.GetString("Knoten2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grad: ähnelt.
        /// </summary>
        public static string KnotenGradText {
            get {
                return ResourceManager.GetString("KnotenGradText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knoten hinzufügen ähnelt.
        /// </summary>
        public static string KnotenHinzufügen {
            get {
                return ResourceManager.GetString("KnotenHinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanten: ähnelt.
        /// </summary>
        public static string KnotenKantenText {
            get {
                return ResourceManager.GetString("KnotenKantenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string KnotenNameText {
            get {
                return ResourceManager.GetString("KnotenNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eltern: ähnelt.
        /// </summary>
        public static string KnotenParentText {
            get {
                return ResourceManager.GetString("KnotenParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl Knoten: ähnelt.
        /// </summary>
        public static string KnotenPickerText {
            get {
                return ResourceManager.GetString("KnotenPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Knoten des Graphen... ähnelt.
        /// </summary>
        public static string KontenLaden {
            get {
                return ResourceManager.GetString("KontenLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt genutzte Dateien: ähnelt.
        /// </summary>
        public static string LetzteDateien {
            get {
                return ResourceManager.GetString("LetzteDateien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
        /// </summary>
        public static string Neu {
            get {
                return ResourceManager.GetString("Neu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string NeueDateiName {
            get {
                return ResourceManager.GetString("NeueDateiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Tab ähnelt.
        /// </summary>
        public static string NeuerTab {
            get {
                return ResourceManager.GetString("NeuerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Fenster ähnelt.
        /// </summary>
        public static string NeuesFenster {
            get {
                return ResourceManager.GetString("NeuesFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Vorlage ähnelt.
        /// </summary>
        public static string NothingTemplate_Header {
            get {
                return ResourceManager.GetString("NothingTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein leerer Graph ohne eine Vorlage. ähnelt.
        /// </summary>
        public static string NothingTemplate_Text {
            get {
                return ResourceManager.GetString("NothingTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        public static string Öffnen {
            get {
                return ResourceManager.GetString("Öffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string Schließen {
            get {
                return ResourceManager.GetString("Schließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string Speichern {
            get {
                return ResourceManager.GetString("Speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort: ähnelt.
        /// </summary>
        public static string Speicherort {
            get {
                return ResourceManager.GetString("Speicherort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Tabelle des Graphen... ähnelt.
        /// </summary>
        public static string TabelleLaden {
            get {
                return ResourceManager.GetString("TabelleLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließe Tab ähnelt.
        /// </summary>
        public static string TabSchließen {
            get {
                return ResourceManager.GetString("TabSchließen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagen: ähnelt.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pollux - neues Fenster ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzen der Texte... ähnelt.
        /// </summary>
        public static string Überstezen {
            get {
                return ResourceManager.GetString("Überstezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vieleck ähnelt.
        /// </summary>
        public static string VieleckTemplate_Header {
            get {
                return ResourceManager.GetString("VieleckTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl an Knoten: ähnelt.
        /// </summary>
        public static string VieleckTemplate_KnotenText {
            get {
                return ResourceManager.GetString("VieleckTemplate_KnotenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Vieleck mit n-Knoten. ähnelt.
        /// </summary>
        public static string VieleckTemplate_Text {
            get {
                return ResourceManager.GetString("VieleckTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort ähnelt.
        /// </summary>
        public static string Weg {
            get {
                return ResourceManager.GetString("Weg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert ähnelt.
        /// </summary>
        public static string Wert {
            get {
                return ResourceManager.GetString("Wert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen! ähnelt.
        /// </summary>
        public static string Willkommen {
            get {
                return ResourceManager.GetString("Willkommen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herzlich Willkommen bei Pollux! ähnelt.
        /// </summary>
        public static string Willkommenstext {
            get {
                return ResourceManager.GetString("Willkommenstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasst uns loslegen, indem wir einen neuen Graphen erstellen. ähnelt.
        /// </summary>
        public static string Willkommenstext2 {
            get {
                return ResourceManager.GetString("Willkommenstext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwischen Tabs springen ähnelt.
        /// </summary>
        public static string ZwischenTabsSpringen {
            get {
                return ResourceManager.GetString("ZwischenTabsSpringen", resourceCulture);
            }
        }
    }
}
